travis:
  secure:
    BINSTAR_TOKEN: rdd3O5jy6LEOV3+UPGXhPuK/66wY0HCwKOaG1AhOQ4NVEhlqgEABjLkvIL5PCVyu6WcbHl1irZ+18Iy9IbnV/SHvVBJcGXk0qCBRnE2veBOf9MQ3cGQs+iJirO6HujzbeqL69FvSo4U+GaBbUoaeMugKw6XqAsaAROhbLEgwWhQErvqiXqTfkg2zP0xvTJ4K2d8NzYPtKxvQ/oa2iv+WXm725rslPsDsVvCpVgyRJGgHIgPn936OleG+c9ZsUhXHoMryR5H0/2RHPgBfhiDeQzxNJ/0/9ACwb9uUIVnGNX79ZUYBfwVmaxV2oF9zV8+Z/mUNRWL304FbDLMQ3LvmiJ9fFClm53usOQRO+FB8zA8axsReY2Ea86UcSmJHFjfR6t8XBW7VFo/6Fsabqp5m+djtbDBI+qilnP3paKRdkXZZsYHepJ6muAslCKM0zK7BBUS3GsfDE8eIfamt8qEdBw+7+p/yMbUFH6kEs6+kxxn3ECLq6w/zELy2l3DCTJk1PXzwFbPOKEhlpKt+8alLunbQQdxIshyI1tQfHz+tZasCJ1HawsbHUBWOAgwH+71csx/VcVUdLE+UqZTdZgb9MhNmyzpkFmZYmennrw/sMr9pt28sOO/tmVDo/+Br0nHemmCWMxjPkCysq9ZdLCmV3AIan5fJufKp4MEgZssI1yI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
