travis:
  secure:
    BINSTAR_TOKEN: RsBC+1x31ggYhe0C63mpqY5PAjyNCraZJ76TD5RDke+MbYxPJdBgWfb4nu0COjDL4qRk74Q8yTpziB1X/zLSGpdSQ3Y1f7WxrFGOhYlFSM662+fC+7mePqmYJP2WszgRlkeQ/cfFWLP5EopWELTt2+1tdb5BPCAlgJmy5Y3bY/dPEsVB7ZLpBzr/yAg8WmgYapaOqC1kUgE2XEGUWUq1G7J5+6JwtjDIG/hcur/Kl9hcZyLizQkpshe4euswnc+r/crBew/AydV5tZR6Gn7LjJhxb/hyWsocMMSaQJCHbn40f/5XhQkxakGXY+qwE2wXc1E9rU5aZcfw3s/s8dvnpBpH5Gp3PUiU8/bNijZi8YX3uHHwuPFT2G02OpvcL3vVgcvlHvHikC+w7PhQ3fmkQz4uUWPFcN3JeKjWGhfnP2kxYHyeIYbNATia0lHOWjbwTYLBRc9LoikFyq/5Y1nqELQYKND7u1FqYqQWtkwBWhjitGXn6o72PYS0Bm8AHFzSEGCH3YhT8UPvrkDKt2Lp/gxlU/4eBYMm0fIpjbNSaaxsF4xZmiwJ5Q7AsLtsjURmtPJ1d1uphjW0qcCUaqC4wU8r4V8IJ4uQSRRXXyLCrcc7TrThgrvWT/dBGJOdLuWC/LkCBVPjhv5GaPxgH1drMBtEelRynq+192hTTzFq8DQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
